### ISSUE TITLE
Is the Client safe for use by multiple goroutines?

### ISSUE THREAD

**Issue by carbocation** [jpillora/go-ogle-analytics#1]
It looks like it probably is, but can you confirm that a Client is safe for concurrent use by multiple goroutines? If so, can you add that to the docs?

**Comment by jpillora** [comment]
This https://github.com/jpillora/go-ogle-analytics/commit/0b3f40f06df668ca8fe2af034a8bc39dc31d87d2 should allow concurrent `Send()`s

**Comment by jpillora** [comment]
Or maybe not, haven't done too much concurrency in Go yet

**Comment by jpillora** [comment]
Will do some tests
