### ISSUE TITLE
[Bug] Pageview events not appearing in real-time monitor

### ISSUE THREAD

**Issue by leeeboo** [jpillora/go-ogle-analytics#4]
I just try 

`gaClient.Send(ga.NewPageview())`

but I can not see in realtime data.

THX!

**Comment by jpillora** [comment]
I think that should work, so I guess it's a bug. If you'd like to help out, could you compare what the [library is sending](https://github.com/jpillora/go-ogle-analytics/blob/master/client.go#L59) to what [GA expects](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters)?

Edit: There could also be a delay in realtime page views?

**Comment by leeeboo** [comment]
@jpillora 
I got logs:

The library sending (Hide some secret):
`av=1.0.0&cid=go-ga&dh=127.0.0.1&dl=http%3A%2F%2F127.0.0.1%2FXXXX&dp=%2FXXXX&t=pageview&tid=UA-XXXX-1&ua=curl%2F7.43.0&uip=127.0.0.1&v=1`

So, I didn 't found difference.

**Comment by jpillora** [comment]
Yeah, looks okay to me, it's possible GA ignores localhost, I'm not sure

**Comment by leeeboo** [comment]
@jpillora 

May be pageview not show in realtime report?

It 's works fine when I replace pageview to event.

**Comment by leeeboo** [comment]
Solved!

Should not use ApplicationVersion.

**Comment by jpillora** [comment]
Ah interesting, thanks for debugging!

**Comment by leeeboo** [comment]
THX!

**Comment by amrew** [comment]
> Solved!
> 
> Should not use ApplicationVersion.

@leeeboo can you explain it? I don't understand what should I do.

**Comment by leeeboo** [comment]
> > Solved!
> 
> > 
> 
> > Should not use ApplicationVersion.
> 
> 
> 
> @leeeboo can you explain it? I don't understand what should I do.

Solved thanks!

**Comment by amrew** [comment]
> > > Solved!
> > 
> > 
> > > 
> > 
> > 
> > > Should not use ApplicationVersion.
> > 
> > 
> > @leeeboo can you explain it? I don't understand what should I do.
> 
> Solved thanks!

@leeeboo I mean I replicate this error too. But I don't understand what should I do to solve it.
What do you mean `Should not use ApplicationVersion.`?
