### ISSUE TITLE
PageView: set Document Location ?

### ISSUE THREAD

**Issue by mh-cbon** [jpillora/go-ogle-analytics#6]
Hi,

I d like to use PageView with the dl parameter.

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dl

The basic PV code produces 

```
cid=go-ga&t=pageview&tid=UA-93911415-1&v=1
```

I tried this to inject the dl parameter,

```go
// within my package.
type myPV struct {
	url string
}

func (h *myPV) Copy() *Pageview {
	c := *h
	return &c
}

func (h *myPV) addFields(v url.Values) error {
	v.Add("dl", h.url)
	return nil
}
```

But that won t work

```
cannot use myPV literal (type *myPV) as type ga.hitType in argument to g.client.Send: *myPV does not implement ga.hitType (missing ga.addFields method) have addFields(url.Values) error want ga.addFields(url.Values) error (build)	
```

I did not figure out how to add that to your lib, i mean, 
i don t get why the generate step adds fields for events/exception but not PV.

When i harcode the change to ga.PageView type directly, things works like a charm.

Can you explain me how i may proceed to patch your lib ?

**Comment by jpillora** [comment]
This package is generated using an old HTML copy of the GA API docs, found here:

https://raw.githubusercontent.com/jpillora/go-ogle-analytics/master/generate/protocol-v1.html

The version you link, is here:

```
view-source:https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters
```

The code that reads the HTML and writes all of the `type-*.go` files is https://github.com/jpillora/go-ogle-analytics/blob/master/generate/protocol.go. The newer HTML is not supported by the current generator.

There are a few options moving forward:

* update the code generator to parse the new API docs HTML
* find a JSON spec / swagger spec for the API and generate using that
* manually add the new types to a new file (not beginning with `type-` as they are all generated)

**Comment by jpillora** [comment]
Actually scrolling down the newer HTML, it's still relatively similar, might not be too hard to fix...

**Comment by mh-cbon** [comment]
mhhhhhh all right i see, thanks for feedback.

Let see, i m interested into one method, one parameter for the moment.

**Comment by mh-cbon** [comment]
for reference, http://stackoverflow.com/questions/42862772/does-ga-proviides-a-standard-api-specification-to-automatically-generate-a-clien, who knows, might be helpful

**Comment by mh-cbon** [comment]
Hi,

im trying to sort this out on my side, but i m blocked.

Essentially, it is because i client.setType is private. 
When i inject a specific hittype to add the missing field, the current implementation can t identify it.
When i create a new Client to try to fix it that, it is not possible to modify the type detection.

seems to me, would be better that hittype implements a GetType() string function, so any type complying with hitype can be identified in Client.setType.

**Comment by jpillora** [comment]
I think ultimate fix (and PR 😄) for this would be update `generate/protocol.go` to support the newer version of the HTML. Alternatively, just maintain your own fork, change package import paths, edit `type-pageview.go` and include the parameters you need into `addFields()`.

Edit: just to clarify, I could expose the interface to allow custom hit-types, however if all hit-types are completely specified in the spec, then that's kind of hacky - better to update the library to include the new hit-types.

**Comment by mh-cbon** [comment]
yeah i totally agree, ultimately it is the right way. 

if i may in my very humble opinion, the generator is a bit intimidating without further investigation.
Maybe it is very easy in practice, indeed, i just dont know about that.

Now i see the good in your approach and i like it very much, but i also think it is up to google to provide a workable resource at first. But it sucks to think in 6 months maybe its half broken again, i put that in balance with the difficulty of update when i think about invest more.

I mean, in the end its all about < 60 lines of code, https://github.com/mh-cbon/report-panic/blob/master/ga/index.go#L14

**Comment by jpillora** [comment]
Yep fair enough. Go is the ultimate pragmatic language, so if you can use
60 lines to avoid patching a 3rd party package then it's definitely worth
it. This package is supposed to be a drop-in mirror of the Measurement
Protocol, I made an issue and hopefully someone picks it up, otherwise I'll
take a look at it again in a few weeks.
